version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby-image
    versions:
    - 2.11.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.11.0
    - 2.11.1
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: framer
    versions:
    - 1.2.23
    - 1.2.24
    - 1.2.25
    - 1.2.26
    - 1.2.27
    - 1.2.28
  - dependency-name: gatsby
    versions:
    - 2.32.10
    - 2.32.11
    - 2.32.3
    - 2.32.4
    - 2.32.6
    - 2.32.8
    - 2.32.9
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 2.14.1
    - 2.14.2
  - dependency-name: gatsby-plugin-offline
    versions:
    - 3.10.0
    - 3.10.1
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 2.12.0
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 2.12.0
